# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches:
      - 'master'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_API_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
      GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: npm install

    - run: npm run build -repository=${GITHUB_REPOSITORY}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: 'gh-pages'
        folder: './build/'
        target-folder: './'
