name: Update JSON

on: push
  # schedule:
  #   # 日本時間17時00分に定期実行
  #   - cron: "0 8 * * *"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date and time
        env:
          TZ: "Asia/Tokyo" # タイムゾーンを指定
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: git checkout
        run: |
          git checkout -b ${{'update-json-'}}${{ steps.date.outputs.date }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update_watcher/requirements.txt
      - name: Run script
        run: |
          python update_watcher/main.py
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update JSON" -a
          git push origin ${{'update-json-'}}${{ steps.date.outputs.date }}
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     title: ${{'Update JSON - '}}${{ steps.date.outputs.date }}
      #     branch: ${{'update-json-'}}${{ steps.date.outputs.date }}
      #     delete-branch: true
      #     base: master
