name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: git checkout
        run: |
          git checkout -b feature/test
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update_watcher/requirements.txt
      - name: Run script
        run: |
          python update_watcher/main.py
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./public/*.json
          git commit -m "Add json" -a
          git push -f origin feature/test
