name: CI

on:
  schedule:
    # 日本時間17時00分に定期実行
    - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: git checkout
        run: |
          git checkout -b ${{'update-json-'}}${{ CURRENT_DATETIME }}
      - uses: actions/setup-python@latest
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update_watcher/requirements.txt
      - name: Run script
        run: |
          python update_watcher/main.py
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update JSON" -a
          git push origin ${{'update-json-'}}${{ CURRENT_DATETIME }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@latest
        with:
          title: ${{'Update JSON - '}}${{ CURRENT_DATETIME }}
          branch: ${{'update-json-'}}${{ CURRENT_DATETIME }}
          base: main
